### ISSUE TITLE
[bug] El largo de varias columnas para nombres y claves es muy corto

### ISSUE THREAD

**Issue by JeanS44** [kurinoku/proyecto-tdi-1#47]
Administrador - campo(Correo_trabajo): Aumentar el largo ya que para ciertos correos se queda corto.
Administrador - campo(Clave_ingreso): Aumentar el largo a 32 para aceptar contraseñas encriptadas.
Ciudadano - campo(Correo_persona): Aumentar el largo ya que para ciertos correos se queda corto.
Ciudadano - campo(Clave_persona): Aumentar el largo a 32 para aceptar contraseñas encriptadas.
Municipalidad - campo(Nombre_municipalidad): Aumentar el largo del campo para que los nombres de municipalidad no se queden cortos.

**Comment by kurinoku** [comment]
En la especificación de requisitos, dice que solo se aceptan [A-Z], [a-z] y el acento, no incluye el espacio, que tal vez es lo deseado.

**Comment by kurinoku** [comment]
El problema que dije anteriormente, está relacionado con #45

**Comment by kurinoku** [comment]
Siendo que las claves son encriptadas, estas deberían cambiarse a char(32) en vez de varchar.

**Comment by kurinoku** [comment]
Esto tiene que ver con #39 y #42
