### ISSUE TITLE
[bug] En formularios, el footer se queda estático

### ISSUE THREAD

**Issue by JeanS44** [kurinoku/proyecto-tdi-1#50]
No puedo intentar poner el footer en la parte inferior, ya que con el método que lo intenté se queda estático todo el tiempo, y esa no es la idea. Intenté todo lo posible pero no me resultó. Por si alguien tiene alguna u otra manera de ubicarlo de buena manera, adaptándose a todas las pantallas.

**Comment by kurinoku** [comment]
¿A que te refieres con estático? ¿Puedes colocar un gif o imagen con un antes y un después?
