### ISSUE TITLE
[bug] Las claves no deben aparecer rellenadas en el formulario

### ISSUE THREAD

**Issue by kurinoku** [kurinoku/proyecto-tdi-1#60]
En este momento, los formularios de editar auto rellenan todos los campos, con los valores anteriores, sin embargo, el problema está con las claves, que también se rellenan, pero como ya no guardamos las contraseñas como tal sino sus hash, lo que se autorellena es el hash de esta, lo que no tiene sentido.

Lo otro, habría que evitar de que al enviar el formulario sin contraseña se actualize la tabla con otra hash de contraseña.

**Comment by Javier-vic** [comment]
EL editar del perfil no rellena con el hash es solo un placeholder de "*****"
